name: test

on:
  push
  
jobs:
  image_building:
    name: image_building
    runs-on: ubuntu-latest
    steps:
      -
        name: Pull repo
        uses: actions/checkout@v1
      -
        name: build image
        run: docker build -t my_image .
      
      
