name: test

on:
  push
  
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - name : Git clone my repo
        uses: actions/checkout@v1
          
      - name : run prereqs
        run: "./prereqs.sh"
        shell: sh
